### PR TITLE
Fix sub-block iteration

### PR DESCRIPTION
**Pull request by ginty**
Quick for for issue with sub-block iteration noted in #61 discussion

### CODE REVIEW

**Comment by info-rchitect** [comment]
@ginty  Thanks for the quick PR.  What is the difference between `_dict` and `__dict__`?

**Comment by info-rchitect** [comment]
@ginty will this fix then enable the same pattern of iteration for regs, memory maps, and address blocks?

**Comment by ginty** [comment]
I think there is no difference between _dict and __dict__, but I found a comment somewhere when trying to work out wtf was going on that mentioned that __dict__ was used by Python (to store metadata) so I changed it to avoid clashing with that.

Made no difference though, the missing __iter__ method was the key.

Oh to be back in Ruby land when all something like would take is `class Proxy < Hash`

**Comment by ginty** [comment]
This will have no effect on any other iterators, this is purely for the sub_blocks. All the others are implemented in Rust, but sub-blocks are uniquely done in Python because that's where a lot of the user application code will go.

**Pull request merged**
